### ISSUE TITLE
exponentiation does not always work

### ISSUE THREAD

**Issue by GassaFM** [spbsu-student-projects/permanent#4]
Simple cases are OK:
~~~~
1
x^(5*7)
~~~~
produces
~~~~
x^35
~~~~

But:
~~~~
1
x^(3^3)
~~~~
gives `x^3` instead of `x^27`.

Similarly,
~~~~
1
x^(-1)
~~~~
gives just `x`.

Either the program should support more cases, or the supported cases should be better documented.

**Comment by Semenar** [comment]
The last example contradicts with both README's and the second to last contradicts with english README. I will add this to russian README.
